### ISSUE TITLE
Problem with blog/bkk19/index.html

### ISSUE THREAD

**Issue by docularxu** [Linaro/Connect#161]
Content and slide on this page mismatches. 
https://connect.linaro.org/resources/bkk19/bkk19-tr07/

Text saying it's about AWS A1. However, the slide is about CCIX.

**Comment by kylekirkby** [comment]
Thanks @docularxu,
I'll take a look at this today.
Cheers,

Kyle

**Comment by kylekirkby** [comment]
https://connect.linaro.org/resources/bkk19/bkk19-tr07/ has been updated with the Correct info! Thanks for letting us know - much appreciated!
