### ISSUE TITLE
Problem with _posts/bkk19/sessions/2019-04-15-bkk19-tr07.md

### ISSUE THREAD

**Issue by docularxu** [Linaro/Connect#164]
The video doesn't show up for me. What I saw in the video box is "AccessDenied xxxx". And if I click on "S3 download", it gives me:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>E914F40E5034B15A</RequestId>
<HostId>
s7Z7DD5k3hsOT/iPY5+eQENr2FEe4OMGxswFNHBgiG/qSRESlRGhwX+816QobRLfhc/Zec9zzGY=
</HostId>
</Error>

Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://connect.linaro.org/resources/bkk19/bkk19-tr07/

**Comment by kylekirkby** [comment]
Hi @docularxu,

Apologies but we're still waiting on this video from our AV contractors. I'll ping this issue once we've got the video.

Thanks,

Kyle

**Comment by kylekirkby** [comment]
Hi @docularxu,

I cannot seem to find this video. I'm going to close this for now but if it surfaces I'll comment on this issue. 

Many thanks,

Kyle
