### ISSUE TITLE
Containerised build fails

### ISSUE THREAD

**Issue by pcolmer** [Linaro/Connect#191]
I've created a new branch to test the new containerised build process. The branch is called `pcolmer-container-builds`.

The build process fails with this Jekyll error:

```
jekyll 3.7.4 | Error:  couldn't find file 'vendor/jquery.js' with type 'application/javascript'
Checked in these paths:
  /gems/gems/bootstrap-sass-3.4.1/assets/stylesheets
  /gems/gems/bootstrap-sass-3.4.1/assets/fonts
  /gems/gems/bootstrap-sass-3.4.1/assets/javascripts
  /srv/source/_assets/css
  /srv/source/_assets/stylesheets
  /srv/source/_assets/images
  /srv/source/_assets/img
  /srv/source/_assets/fonts
  /srv/source/_assets/javascripts
  /srv/source/_assets/js
  /srv/source/assets/js
  /srv/source/assets/js/vendor
  /srv/source/assets/js/app
  /srv/source/assets/images
  /srv/source/assets/images/sponsors
  /srv/source/assets/images/featured-images
  /srv/source/assets/images/people
  /srv/source/assets/images/speakers
  /srv/source/assets/images/content
  /srv/source/assets/images/blog
  /srv/source/assets/css
```

The fact that it can't find a Javascript file suggests that this is a problem with the contents of the repo which hasn't been detected so far because builds have taken place on an "unclean" directory, i.e. where bits and pieces have been left behind.

I've also noticed that, like 96boards.ai, there are a bunch of assets being generated in the repo directory rather than the built-site directory.

To reproduce the build process, clone the repo into a clean directory and go:

```
git checkout pcolmer-container-builds
./build-site.sh
```

**Comment by kylekirkby** [comment]
Hi Philip - taking a look at this now and I'm getting:

 kyle@gibson  ~/Documents/work/websites/connect.linaro.org   remotes/origin/pcolmer-container-builds ?  sudo ./build-site.sh                       126 ↵
Cannot find output directory

Any ideas ? I've also tried creating the built_site dir:
`mkdir built_site` within the Connect.l.o repo.

**Comment by pcolmer** [comment]
Don't use `sudo` ...

**Comment by kylekirkby** [comment]
Voila :D 
 kyle@gibson  ~/Documents/work/websites/connect.linaro.org   remotes/origin/pcolmer-container-builds ?  ./build-site.sh                            125 ↵
Cannot find output directory

**Comment by pcolmer** [comment]
Can you try:

`git pull linaroitsjekyllbuild`

to make sure you've got the latest container?

**Comment by kylekirkby** [comment]
So the issue is occuring because the Jekyll theme paths aren't being used for locating assets. 

```
/srv/source/assets/js/package-resources-blog.js:1: couldn't find file 'vendor/jquery.js' with type 'application/javascript' (Sprockets::FileNotFound)
Checked in these paths: 
  /gems/gems/bootstrap-sass-3.4.1/assets/stylesheets
  /gems/gems/bootstrap-sass-3.4.1/assets/fonts
  /gems/gems/bootstrap-sass-3.4.1/assets/javascripts
  /srv/source/_assets/css
  /srv/source/_assets/stylesheets
  /srv/source/_assets/images
  /srv/source/_assets/img
  /srv/source/_assets/fonts
  /srv/source/_assets/javascripts
  /srv/source/_assets/js
  /srv/source/assets/js
  /srv/source/assets/js/vendor
  /srv/source/assets/js/app
  /srv/source/assets/images
  /srv/source/assets/images/sponsors
  /srv/source/assets/images/featured-images
  /srv/source/assets/images/people
  /srv/source/assets/images/speakers
  /srv/source/assets/images/content
  /srv/source/assets/images/blog
  /srv/source/assets/css
```
The paths should also check a path along the lines of /home/kyle/.rvm/gems/ruby-2.6.0/gems/jumbo-jekyll-theme-5.2.1. I may need to update the jekyll-theme-assets plugin we are using to ensure that the plugin is looking in the correct path.

**Comment by pcolmer** [comment]
OK - the root cause of this was that "gems" was in Jekyll's exclude list. Since the container build process mounts ".gems" from the host onto "/gems" in the container, Jekyll was excluding anything on that path (although that doesn't explain the first three paths listed in the output above).

So, removing that line from the exclude list allows the build to work.

**Comment by kylekirkby** [comment]
@pcolmer - thanks for the help with this one!! :1st_place_medal:
