### ISSUE TITLE
Can't build with Jekyll 3.7.3 (Invalid US-ASCII character "\xEE")

### ISSUE THREAD

**Issue by morancj** [Linaro/Connect#20]
Build many files, then errors with:
```
  Rendering Markup: assets/css/main-about.scss
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main-about.scss':
                    Invalid US-ASCII character "\xEE" on line 51
jekyll 3.7.3 | Error:  Invalid US-ASCII character "\xEE" on line 51
```

**Comment by morancj** [comment]
Relates to https://github.com/Linaro/website/issues/264?

**Comment by kylekirkby** [comment]
Yep - just doing a PR with charset's added to the scss packages :) Sorry about that!

**Comment by kylekirkby** [comment]
https://github.com/Linaro/Connect/pull/21

**Comment by morancj** [comment]
This breaks in minimal (ish!) Docker Linux images without the necessary locales installed and LANG/LC_ALL set. See also: https://github.com/Starefossen/docker-github-pages/issues/2
