### ISSUE TITLE
Problem with _posts/san19/sessions/2019-09-11-san19-415.md

### ISSUE THREAD

**Issue by etienne-lms** [Linaro/Connect#296]
Resources for san19-415 and  san19-203 are swapped.

https://connect.linaro.org/resources/san19/san19-415/
  SAN19-415 - Trusted Firmware Project Update

https://connect.linaro.org/resources/san19/san19-203/
  SAN19-203 - DMA-Buf Developments

**Comment by etienne-lms** [comment]
sorry: video & presentation url swapped between the 2, not their respective resources page.

**Comment by kylekirkby** [comment]
Hi @etienne-lms,

These pages have been updated to point to the correct resources :) 

Many thanks,

Kyle

**Comment by etienne-lms** [comment]
thanks

**Comment by kylekirkby** [comment]
np!
