### ISSUE TITLE
Suggestion for _pages/homepage.md: disable the automatic carousel rotation timer when user selects page

### ISSUE THREAD

**Issue by morancj** [Linaro/Connect#298]
Suggestion: if the viewer clicks a specific page on the carousel, disable the automatic rotation timer. It is annoying if e.g. one wants to look at the second page of speaker details to have the website jump back to the first page after some seconds.

**Comment by kylekirkby** [comment]
@morancj - where on the website does this occur?

**Comment by morancj** [comment]
@kylekirkby Pick a carousel, any carousel. :smile: The one near the top of this page is an example.

**Comment by kylekirkby** [comment]
Yes. All Owl Carousel instances should have the "Pause on hover" option set to true. I'll add this to JIRA under my Jekyll Theme Project. :)

**Comment by morancj** [comment]
@kylekirkby This issue is not about "on hover", it's that when a viewer selects a particular slide in the carousel, that slide should remain displayed until the viewer selects another slide or navigates away from the page.

**Comment by kylekirkby** [comment]
> @kylekirkby This issue is not about "on hover", it's that when a viewer selects a particular slide in the carousel, that slide should remain displayed until the viewer selects another slide or navigates away from the page.

Yes. When you "select a particular slide" you've already triggered the "hover" mouse event...

**Comment by morancj** [comment]
@kylekirkby As an end user, I don't particularly care how it's implemented. :wink: There is no need for hover events here, except for changing the colour of the buttons on mouseover I guess. Click the `<` or `>` arrows under the carousel and note how the slide can immediately change if your click timing is unlucky (presumably near the time an auto-rotation event is due). I hope this clarifies my issue with these carousels.

**Comment by kylekirkby** [comment]
Arhh I see. No worries.

**Comment by kylekirkby** [comment]
No longer an issue. Closing :)
