### ISSUE TITLE
Needs indexing to help navigate

### ISSUE THREAD

**Issue by daniel-thompson** [Linaro/Connect#304]
In summary the way the talks are presented as cards is simply unfair to anyone whose session was not first thing on Monday!

Even digging through to find a Wednesday keynote when you *know* what session one is looking for is needless painful.

Some kind of index for the talks is needed allowing quick navigation. Ideally three indexes (by day/time, alphabetic by presenter, alphabetic by talk title) but, to be honest, even a quick "Mon/Tue/Wed/Thu/Fri" shortcut as the landing page would make a big difference.

Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://connect.linaro.org/resources/san19/sessions/2/index.html

**Comment by kylekirkby** [comment]
Hi @daniel-thompson,

Thanks for the feedback - we have a resources table available here:

**Comment by daniel-thompson** [comment]
Cool... ish.

Perhaps the problem is not with the side I filed this bug against but some of our other properties pointing to the wrong place!

 * Google search for as much as I could remember (name of presenter, that is was a keynote and that is was at connect).
 * Land at https://linaroconnectsandiego.sched.com/bryanh (which was the best looking think near the top of the search)
 * Follow links found on the above page.

Feels like sched header isn't pointing to the right place!

**Comment by kylekirkby** [comment]
Hi @daniel-thompson,

Sorry but I'm struggling to understand what you mean by the above - could you elaborate? 

Cheers,

Kyle

**Comment by daniel-thompson** [comment]
> Sorry but I'm struggling to understand what you mean by the above - could you elaborate?

My fault, looks like I detailed the text saying "Let me show how I landed on this page" before the bulleted list.

The short version is that you have referred me to an excellent and easy to navigate summary of the sessions at connect... but the links from our sched.com site (which is currently what ranks high on Google) don't point the excellent summary!

**Comment by kylekirkby** [comment]
Arhh perfect! Let me see what I can do :) Thanks @daniel-thompson !

**Comment by kylekirkby** [comment]
Hi @daniel-thompson,

I've looked at some of the search results that Google is returning and, for speakers, sched results are listed higher than related connect.linaro.org pages. This could potentially be due to the speakers having **their own page on sched** and just being _featured_ on the connect.linaro.org resources pages. When searching for individual sessions, a lot of the results are connect.linaro.org first. I've also added a link to the connect.linaro.org/resources/san19/ page on the linaroconnectsandiego.sched.com homepage. Is there anything else you think we should do or can I close this issue?

Kind regards,

Kyle

**Comment by daniel-thompson** [comment]
> Is there anything else you think we should do or can I close this issue?

Sticking to the example case:
https://linaroconnectsandiego.sched.com/bryanh

Right at the top there is a line "Linaro Connect resources will be available here during and after Connect!" where the "here" links to the difficult to navigate card based web page.

Is that text part of a header and easy to change or did it get burned into every page? If would better for that banner to link to a good quality index.

PS the situation will slowly get better as the searching engines start to fill up but it would still be good to avoid sched linking to difficult to navigate pages.

**Comment by kylekirkby** [comment]
Hi @daniel-thompson,

I've updated the link to go to [https://connect.linaro.org/resources/san19/](https://connect.linaro.org/resources/san19/) instead. :)

BR,

Kyle

**Comment by daniel-thompson** [comment]
In that case, let's call this done!

**Comment by kylekirkby** [comment]
Thanks @daniel-thompson !
