### ISSUE TITLE
Problem with _posts/bkk16/2016-02-22-bkk16-110.markdown

### ISSUE THREAD

**Issue by wmnt** [Linaro/Connect#377]
Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://connect.linaro.org/resources/bkk16/bkk16-110/

The YouTube link doesn't seem to work. A playback error is reported.

**Comment by kylekirkby** [comment]
Hi @wmnt,
Thanks for reporting the issue! Sadly this session had no video but the web page was misleading!
Many thanks!
Kyle
