### ISSUE TITLE
Problem with _posts/sfo15/2015-09-24-sfo15-406-arm-fdpic-toolset-kernel-libraries-for-cortex-m-cortex-r-mmuless-cores.markdown

### ISSUE THREAD

**Issue by thejh** [Linaro/Connect#572]
Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://connect.linaro.org/resources/sfo15/sfo15-406-arm-fdpic-toolset-kernel-libraries-for-cortex-m-cortex-r-mmuless-cores/

The "Download Presentation" button leads to an "AccessDenied" AWS error.

**Comment by pcolmer** [comment]
Thanks, @thejh.

**Comment by kylekirkby** [comment]
Resources now available.
