### ISSUE TITLE
Problem with _pages/call_for_proposals.md

### ISSUE THREAD

**Issue by ZhengZhenyu** [Linaro/Connect#775]
There seems to be no detailed information about each track, made it quite difficult for protential submitters.

Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://connect.linaro.org/cfp/

**Comment by kristinedill** [comment]
hi @ZhengZhenyu when you click on the submit proposal links it brings you to the CFP page with all the details to submit including the track list. 

I will add the track list to the CFP page as well. 

Thanks, 

Kristine
